[workspace]

members = [
    "shell",
    "simdisk",
]

[workspace.dependencies]
log = "0.4.20"
pretty_env_logger = "0.5.0"
tokio = { version = "1.32.0", features = ["full"] }
utils = {path = "lib"}

[profile.release]
lto = true
strip = true
incremental = true