name: Build and Release Rust Projects

on: 
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Linux Target
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu

    - name: Upload Linux shell
      uses: actions/upload-artifact@v3
      with:
        name: shell
        path: target/x86_64-unknown-linux-gnu/release/shell

    - name: Upload Linux simdisk
      uses: actions/upload-artifact@v3
      with:
        name: simdisk
        path: target/x86_64-unknown-linux-gnu/release/simdisk

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Windows Target
      run: |
        cargo build --release --target x86_64-pc-windows-gnu

    - name: Upload Windows shell
      uses: actions/upload-artifact@v3
      with:
        name: shell.exe
        path: target/x86_64-pc-windows-gnu/release/shell.exe
    
    - name: Upload Windows simdisk
      uses: actions/upload-artifact@v3
      with:
        name: simdisk.exe
        path: target/x86_64-pc-windows-gnu/release/simdisk.exe

  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build MacOS Target
      run: |
        cargo build --release --target x86_64-apple-darwin
        mv target/x86_64-apple-darwin/release/shell target/x86_64-apple-darwin/release/shell.app
        mv target/x86_64-apple-darwin/release/simdisk target/x86_64-apple-darwin/release/simdisk.app

    - name: Upload MacOS shell
      uses: actions/upload-artifact@v3
      with:
        name: shell.app
        path: target/x86_64-apple-darwin/release/shell.app

    - name: Upload MacOS simdisk
      uses: actions/upload-artifact@v3
      with:
        name: simdisk.app
        path: target/x86_64-apple-darwin/release/simdisk.app

  build-mac-arm:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build ARM MacOS Target
      run: |
        rustup target add aarch64-apple-darwin
        cargo build --release --target aarch64-apple-darwin
        mv target/x86_64-apple-darwin/release/shell target/x86_64-apple-darwin/release/shell_arm64.app
        mv target/x86_64-apple-darwin/release/simdisk target/x86_64-apple-darwin/release/simdisk_arm64.app

    - name: Upload Arm MacOS shell
      uses: actions/upload-artifact@v3
      with:
        name: shell_arm64.app
        path: target/aarch64-apple-darwin/release/shell_arm64.app

    - name: Upload Arm MacOS simdisk
      uses: actions/upload-artifact@v3
      with:
        name: simdisk_arm64.app
        path: target/aarch64-apple-darwin/release/simdisk_arm64.app

        
  release:
    needs: [build-linux, build-windows, build-mac, build-mac-arm]
    runs-on: ubuntu-latest

    env: 
      VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        with:
          path: bins

      - name: Archive Linux Binaries
        run: |
          zip -j $FILENAME bins/shell/shell bins/simdisk/simdisk
        env:
          FILENAME: SimpleFS_x86_64-linux_${{env.VERSION}}.zip

      - name: Archive Windows Binaries
        run: |
          zip -j $FILENAME bins/shell.exe/shell.exe bins/simdisk.exe/simdisk.exe
        env:
          FILENAME: SimpleFS_x86_64-windows_${{env.VERSION}}.zip

      - name: Archive MacOS Binaries
        run: |
          zip -j $FILENAME bins/shell.app/shell.app bins/simdisk.app/simdisk.app
        env:
          FILENAME: SimpleFS_x86_64-apple_${{env.VERSION}}.zip

      - name: Archive ARM MacOS Binaries
        run: |
          zip -j $FILENAME bins/shell_arm64.app/shell_arm64.app bins/simdisk_arm64.app/simdisk_arm64.app
        env:
          FILENAME: SimpleFS_aarch64-apple_${{env.VERSION}}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.zip